nodeLinker: node-modules

# Enforce a minimal age for npm packages before they can be added/updated
npmMinimalAgeGate: 7

# Packages to ignore the minimal age gate. These are packages we vet ourselves.
npmPreapprovedPackages:
  - '@sofie-automation/*'
